spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: java
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
            decode404: true

            server:
              port: 8000

           #   servlet:
            #    context-path: /book-service

            feign:
              client:
                config:
                  default:
                    connectTimeout: 5000
                    readTimeout: 5000
                    loggerLevel: basic

           # user-service:
            #  username: java
             # password: root